# -*- coding: utf-8 -*-
"""4-лабка урмат продолжение .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10f_jiRLJzWkXR6j7wSUtFptlQ0frUFes
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# ============================================
# ПОДГОТОВКА ДАННЫХ
# ============================================

# Вариант 1: Если данные уже загружены в df
# (раскомментируйте, если df уже существует)
# if 'df' not in locals():
#     df = pd.read_csv('student_clusters.csv')  # или другой файл

# Вариант 2: Загрузить данные из файла
try:
    # Попробуйте загрузить из файла (укажите правильный путь)
    df = pd.read_csv('student_data_processed.csv')
    print(f"✅ Данные загружены из файла: {len(df)} записей")
except FileNotFoundError:
    # Если файл не найден, создаем пример данных
    print("⚠️ Файл не найден. Создаю пример данных...")
    np.random.seed(42)
    n = 500

    df = pd.DataFrame({
        'gender_male': np.random.binomial(1, 0.5, n),
        'activities_medium': np.random.binomial(1, 0.4, n),
        'activities_high': np.random.binomial(1, 0.3, n),
        'living_семья': np.random.binomial(1, 0.5, n),
        'living_общежитие': np.random.binomial(1, 0.3, n),
        'living_самостоятельно': np.random.binomial(1, 0.2, n),
        'study_hours': np.random.normal(5, 2, n),
        'study_load': np.random.uniform(3, 8, n),
        'sleep_hours': np.random.normal(7, 1.5, n),
        'fatigue': np.random.uniform(3, 9, n),
        'free_time': np.random.uniform(2, 8, n),
        'sport': np.random.uniform(0, 5, n),
        'satisfaction': np.random.uniform(3, 10, n),
        'procrastination': np.random.uniform(2, 9, n),
        'deadline_success': np.random.uniform(4, 10, n),
        'stress': np.random.uniform(3, 9, n),
        'interest_for_study': np.random.uniform(3, 10, n)
    })
    print(f"✅ Создано {len(df)} примеров данных")

# Проверяем наличие необходимых признаков
required_features = ['gender_male', 'activities_medium', 'activities_high',
                     'living_семья', 'living_общежитие', 'living_самостоятельно',
                     'study_hours', 'study_load', 'sleep_hours', 'fatigue',
                     'free_time', 'sport', 'satisfaction', 'procrastination',
                     'deadline_success', 'stress', 'interest_for_study']

missing_features = [f for f in required_features if f not in df.columns]
if missing_features:
    print(f"⚠️ Отсутствуют признаки: {missing_features}")
    # Используем только доступные признаки
    features = [f for f in required_features if f in df.columns]
    print(f"✅ Использую {len(features)} признаков: {features}")
else:
    features = required_features
    print(f"✅ Все признаки присутствуют: {len(features)}")

# ============================================
# ЭТАП 3: КЛАСТЕРИЗАЦИЯ (упрощенная версия)
# ============================================

print("\n" + "="*50)
print("ЭТАП 3: КЛАСТЕРИЗАЦИЯ")
print("="*50)

# 1. ПОДГОТОВКА ДАННЫХ
X = df[features].values
X_scaled = StandardScaler().fit_transform(X)

# 2. PCA и t-SNE
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

# Проверяем размер выборки для t-SNE
perplexity = min(30, len(X_scaled) - 1)
tsne = TSNE(n_components=2, random_state=42, perplexity=perplexity)
X_tsne = tsne.fit_transform(X_scaled)

print(f"✅ Данные: {len(X)} объектов, {len(features)} признаков")
print(f"✅ PCA объясняет {pca.explained_variance_ratio_.sum():.1%} дисперсии")

# 3. K-MEANS (с подбором k)
print("\n📊 K-MEANS - подбор числа кластеров:")

K_range = range(2, min(8, len(X_scaled) - 1))
scores = []
for k in K_range:
    labels = KMeans(n_clusters=k, random_state=42, n_init=10).fit_predict(X_scaled)
    scores.append(silhouette_score(X_scaled, labels))
    print(f"  k={k}: silhouette={scores[-1]:.3f}")

best_k = K_range[np.argmax(scores)]
print(f"\n✨ Лучшее k = {best_k}")

# K-Means финальный
kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
df['Cluster_KMeans'] = kmeans.fit_predict(X_scaled)

# Графики K-Means
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
scatter1 = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=df['Cluster_KMeans'],
                       cmap='viridis', alpha=0.7, s=80)
plt.title(f'K-Means (k={best_k}) на PCA')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.colorbar(scatter1)

plt.subplot(1, 2, 2)
scatter2 = plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=df['Cluster_KMeans'],
                       cmap='viridis', alpha=0.7, s=80)
plt.title(f'K-Means (k={best_k}) на t-SNE')
plt.xlabel('t-SNE 1')
plt.ylabel('t-SNE 2')
plt.colorbar(scatter2)
plt.tight_layout()
plt.show()

# 4. ИЕРАРХИЧЕСКАЯ (с дендрограммой)
print("\n📊 ИЕРАРХИЧЕСКАЯ КЛАСТЕРИЗАЦИЯ")

# Дендрограмма (для больших данных берем подвыборку)
sample_size = min(30, len(X_scaled))
if len(X_scaled) > 100:
    print(f"⚠️ Для дендрограммы использована выборка из {sample_size} объектов")
    sample_indices = np.random.choice(len(X_scaled), sample_size, replace=False)
    X_sample = X_scaled[sample_indices]
else:
    X_sample = X_scaled

plt.figure(figsize=(12, 5))
linked = linkage(X_sample, method='ward')
dendrogram(linked, truncate_mode='lastp', p=min(30, sample_size),
           leaf_rotation=90, leaf_font_size=10)
plt.title('Дендрограмма')
plt.xlabel('Индексы')
plt.ylabel('Расстояние')
plt.axhline(y=5, color='r', linestyle='--')
plt.tight_layout()
plt.show()

# Иерархическая кластеризация
hier = AgglomerativeClustering(n_clusters=best_k, metric='euclidean', linkage='ward')
df['Cluster_Hier'] = hier.fit_predict(X_scaled)

# Графики иерархической
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
scatter3 = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=df['Cluster_Hier'],
                       cmap='plasma', alpha=0.7, s=80)
plt.title(f'Иерархическая (k={best_k}) на PCA')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.colorbar(scatter3)

plt.subplot(1, 2, 2)
scatter4 = plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=df['Cluster_Hier'],
                       cmap='plasma', alpha=0.7, s=80)
plt.title(f'Иерархическая (k={best_k}) на t-SNE')
plt.xlabel('t-SNE 1')
plt.ylabel('t-SNE 2')
plt.colorbar(scatter4)
plt.tight_layout()
plt.show()

# 5. DBSCAN (опционально)
print("\n📊 DBSCAN (поиск выбросов)")

best = None
best_score = -1

eps_values = [0.8, 1.0, 1.2, 1.5]
min_samples_values = [3, 4, 5]

for eps in eps_values:
    for min_samples in min_samples_values:
        labels = DBSCAN(eps=eps, min_samples=min_samples).fit_predict(X_scaled)
        n_clust = len(set(labels)) - (1 if -1 in labels else 0)
        n_noise = list(labels).count(-1)

        if n_clust >= 2 and n_clust <= 6:
            mask = labels != -1
            if sum(mask) > 1:  # нужно минимум 2 точки для silhouette
                try:
                    score = silhouette_score(X_scaled[mask], labels[mask])
                    print(f"  eps={eps}, min_samples={min_samples}: кластеров={n_clust}, шум={n_noise}, score={score:.3f}")
                    if score > best_score:
                        best_score, best = score, (eps, min_samples, labels)
                except:
                    print(f"  eps={eps}, min_samples={min_samples}: кластеров={n_clust}, шум={n_noise}")
            else:
                print(f"  eps={eps}, min_samples={min_samples}: кластеров={n_clust}, шум={n_noise}")
        else:
            print(f"  eps={eps}, min_samples={min_samples}: кластеров={n_clust}, шум={n_noise}")

if best:
    eps, ms, labels = best
    df['Cluster_DBSCAN'] = labels
    print(f"\n✨ Лучший DBSCAN: eps={eps}, min_samples={ms}, шум={list(labels).count(-1)}")

    plt.figure(figsize=(12, 4))
    plt.subplot(1, 2, 1)
    scatter5 = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=df['Cluster_DBSCAN'],
                          cmap='tab10', alpha=0.7, s=80)
    plt.title('DBSCAN на PCA')
    plt.xlabel('PC1')
    plt.ylabel('PC2')
    plt.colorbar(scatter5)

    plt.subplot(1, 2, 2)
    scatter6 = plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=df['Cluster_DBSCAN'],
                          cmap='tab10', alpha=0.7, s=80)
    plt.title('DBSCAN на t-SNE')
    plt.xlabel('t-SNE 1')
    plt.ylabel('t-SNE 2')
    plt.colorbar(scatter6)
    plt.tight_layout()
    plt.show()

# 6. АНАЛИЗ КЛАСТЕРОВ
print("\n📊 АНАЛИЗ КЛАСТЕРОВ (K-Means):")

for c in sorted(df['Cluster_KMeans'].unique()):
    d = df[df['Cluster_KMeans'] == c]
    print(f"\nКластер {c} ({len(d)} чел):")
    if 'stress' in df.columns:
        print(f"  Стресс: {d['stress'].mean():.2f}")
    if 'satisfaction' in df.columns:
        print(f"  Удовл: {d['satisfaction'].mean():.2f}")
    if 'sleep_hours' in df.columns:
        print(f"  Сон: {d['sleep_hours'].mean():.1f}ч")
    if 'sport' in df.columns:
        print(f"  Спорт: {d['sport'].mean():.2f}")
    if 'gender_male' in df.columns:
        print(f"  Муж: {d['gender_male'].mean()*100:.0f}%")

# Сравнение методов
if 'Cluster_Hier' in df.columns:
    print(f"\n📊 Сравнение K-Means и Иерархической:")
    print(pd.crosstab(df['Cluster_KMeans'], df['Cluster_Hier']))

# Сохранение
df.to_csv('student_clusters.csv', index=False)
print("\n✅ Результаты сохранены в 'student_clusters.csv'")

# ВЫВОДЫ
print("\n" + "="*50)
print("ВЫВОДЫ ПО КЛАСТЕРИЗАЦИИ")
print("="*50)

n_dbscan_outliers = list(df['Cluster_DBSCAN']).count(-1) if 'Cluster_DBSCAN' in df.columns else 'N/A'
print(f"""
• Оптимальное число кластеров: k = {best_k}
• K-Means выделил {best_k} группы студентов
• Дендрограмма подтверждает структуру данных
• DBSCAN нашел {n_dbscan_outliers} выбросов
• Кластеры различаются по стрессу, удовлетворенности и образу жизни
""")

# Дополнительная статистика
print("📊 Размер кластеров (K-Means):")
for c in sorted(df['Cluster_KMeans'].unique()):
    size = len(df[df['Cluster_KMeans'] == c])
    percentage = (size / len(df)) * 100
    print(f"  Кластер {c}: {size} студентов ({percentage:.1f}%)")