# -*- coding: utf-8 -*-
"""4лабка вроде конецурмат.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCZ-TvMziNaPbPqtP4pNTLk_oRFdnqoh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import warnings
warnings.filterwarnings('ignore')

# ============================================
# ЗАГРУЗКА ДАННЫХ (75 студентов)
# ============================================
data = {
    'gender_male': [0,1,1,1,0,0,0,0,1,1,1,1,0,0,0,1,1,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,1,0,1,1,1,0,0,1,1,0,1,0,0,1,1,1,0,0,0,1,1,0,0,1,0,1,0,1,0,0,1,0,0,1,1,1,1,0,1,0],
    'activities_medium': [1,0,0,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,0,1,0,1,1,0,0,1,1,0,0,1,0,1,1,1,0,1,1,0,1,0,0,0,1,1,1,1,0,1,1,0,1,0,1,0,1,0,1,1,0,0,1,1,0,0],
    'activities_high': [0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,1,1,0,0,1,1],
    'living_семья': [1,1,1,1,1,0,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,1,0,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,0,1,0,0,1,1,1,1,1,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,0,1],
    'living_общежитие': [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,1,1,0,0,1,0],
    'living_самостоятельно': [0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    'study_hours': [2,3,1,2,1,3,2,1,2,1,2,2,3,3,1,1,2,2,1,2,1,1,2,2,1,3,2,2,1,2,2,1,1,2,3,3,2,1,2,1,1,3,2,2,1,3,1,2,3,2,3,2,3,2,2,2,2,1,2,2,1,1,2,2,1,2,2,3,2,3,1,1,2,1,2],
    'study_load': [1,3,1,2,3,3,3,2,2,2,2,3,3,2,1,2,2,2,2,3,1,1,2,2,2,2,2,2,2,2,2,2,1,2,3,2,3,2,2,2,2,2,2,2,2,3,2,2,3,1,3,3,3,2,1,2,3,2,2,2,2,2,3,2,2,2,2,1,2,2,2,1,2,3,2],
    'sleep_hours': [2,2,1,1,2,1,2,2,2,2,1,1,1,1,1,2,1,1,1,1,3,2,2,2,2,3,2,2,3,3,3,2,1,2,2,2,1,2,3,1,1,1,2,3,2,2,1,1,1,1,2,3,1,3,2,3,3,2,2,2,1,2,2,2,2,2,3,2,1,1,3,2,1,1,1],
    'fatigue': [2,1,1,2,3,3,2,3,2,2,2,3,3,2,3,2,3,2,3,3,1,3,3,3,2,2,2,2,2,2,2,2,3,3,3,3,2,2,2,2,2,3,2,2,2,1,3,3,1,3,2,1,3,2,3,3,2,3,2,1,2,3,3,2,2,1,3,3,1,2,1,3,3,2,1],
    'free_time': [3,1,2,2,1,1,3,1,2,1,2,1,2,3,3,3,2,1,1,1,1,2,2,2,2,2,2,2,3,1,3,2,2,2,3,3,1,3,2,3,1,1,2,3,2,1,2,3,2,3,2,2,2,3,1,2,3,3,2,3,1,1,2,3,2,3,1,2,3,3,3,2,1,2,1],
    'sport': [3,3,2,1,1,1,2,1,2,1,2,3,1,2,2,2,3,2,1,2,1,1,1,1,1,2,1,2,2,2,3,3,1,2,1,2,2,1,1,2,2,2,3,3,1,2,1,1,2,1,2,2,1,1,2,2,1,2,1,2,1,2,1,2,1,2,2,1,2,3,1,3,2,1,1],
    'satisfaction': [3,2,3,2,2,2,2,1,2,2,3,2,1,2,1,3,2,2,1,1,1,2,2,2,2,2,3,3,3,2,3,3,2,2,1,1,2,2,1,2,1,2,1,2,2,2,1,2,2,2,1,2,1,2,2,2,2,2,2,2,3,2,2,3,1,3,3,2,2,2,1,3,1,3,3],
    'procrastination': [3,2,2,1,2,2,1,3,2,1,2,1,3,2,2,3,2,3,3,3,3,3,3,2,2,2,2,2,1,2,3,2,3,2,1,3,2,1,1,3,2,1,3,2,1,2,3,2,1,2,2,2,2,3,3,1,2,3,1,3,3,2,2,2,3,2,3,2,1,2,2,2,2,2,1],
    'deadline_success': [2,3,1,2,2,2,3,2,2,2,1,1,2,2,2,2,3,1,1,2,3,2,2,2,2,3,3,3,3,2,3,2,1,1,3,1,2,3,1,2,2,2,3,2,2,2,2,2,3,3,2,2,3,1,2,3,1,1,2,2,2,2,2,3,2,2,3,3,3,2,2,2,2,3,2],
    'stress': [2,2,1,2,3,3,2,3,2,3,2,3,2,3,3,3,2,2,3,2,3,3,3,3,2,2,2,2,1,2,2,1,1,3,2,2,1,3,2,2,2,2,2,2,2,3,3,3,2,2,3,3,3,3,3,2,2,3,1,2,2,2,2,2,2,2,3,3,2,2,2,3,3,2,2],
    'interest_for_study': [1,3,2,2,2,3,2,2,2,1,3,1,2,3,2,2,2,2,2,2,1,2,2,3,3,2,3,3,3,3,3,3,2,3,2,3,2,2,3,3,2,3,2,2,1,3,2,2,3,3,3,2,2,2,3,3,2,2,1,3,1,3,2,2,1,2,2,3,2,3,2,2,3,2,1]
}

df = pd.DataFrame(data)
n = len(df)

print("="*60)
print(f"✅ ЗАГРУЖЕНО {n} СТУДЕНТОВ")
print("="*60)
print(f"\nКолонки в данных: {list(df.columns)}")
print(f"Признаков: {len(df.columns)}")

# Добавляем категории
df['gender'] = df['gender_male'].map({1:'Мужской',0:'Женский'})
df['activity'] = df['activities_high'].map({1:'Высокая',0:'Низкая/Средняя'})
df['living'] = df['living_семья'].map({1:'С семьей',0:'Отдельно'})

# ============= 1. БАЗОВАЯ СТАТИСТИКА =============
print("\n📊 ОСНОВНЫЕ ПОКАЗАТЕЛИ:")
print(f"  Стресс: {df['stress'].mean():.2f}/3")
print(f"  Удовлетворенность: {df['satisfaction'].mean():.2f}/3")
print(f"  Сон: {df['sleep_hours'].mean():.2f}/3")
print(f"  Учеба: {df['study_hours'].mean():.2f}/3")
print(f"  Спорт: {df['sport'].mean():.2f}/3")
print(f"  Прокрастинация: {df['procrastination'].mean():.2f}/3")

high_stress = len(df[df['stress']>2])
print(f"\n⚠️ Студентов с высоким стрессом (>2): {high_stress} ({high_stress/n*100:.0f}%)")

# ============= 2. КОРРЕЛЯЦИИ =============
print("\n📊 КОРРЕЛЯЦИЯ СО СТРЕССОМ:")

# Все числовые колонки для корреляции
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
# Убираем 'stress' из списка для корреляции
corr_cols = [col for col in numeric_cols if col != 'stress']

# Рассчитываем корреляцию
correlations = {}
for col in corr_cols:
    correlations[col] = df[col].corr(df['stress'])

# Сортируем
corr_series = pd.Series(correlations).sort_values()

print("\n  🔽 СНИЖАЮТ стресс (отрицательная корреляция):")
negative_corr = corr_series[corr_series < 0]
for i, (var, corr_val) in enumerate(negative_corr.head(3).items()):
    print(f"    {i+1}. {var}: {corr_val:.3f}")

print("\n  🔼 ПОВЫШАЮТ стресс (положительная корреляция):")
positive_corr = corr_series[corr_series > 0]
for i, (var, corr_val) in enumerate(positive_corr.tail(3).iloc[::-1].items()):
    print(f"    {i+1}. {var}: {corr_val:.3f}")

# ============= 3. ГЕНДЕРНЫЕ РАЗЛИЧИЯ =============
print("\n📊 ГЕНДЕРНЫЕ РАЗЛИЧИЯ:")
male = df[df['gender_male']==1]
female = df[df['gender_male']==0]
print(f"  Мужчины: {len(male)} ({len(male)/n*100:.0f}%)")
print(f"  Женщины: {len(female)} ({len(female)/n*100:.0f}%)")

for metric in ['stress','satisfaction','sleep_hours','sport']:
    if metric in df.columns:
        t_stat, p_val = stats.ttest_ind(male[metric], female[metric])
        diff = male[metric].mean() - female[metric].mean()
        if p_val < 0.05:
            sign = "✓" if diff>0 else "✓"
            print(f"  {sign} {metric}: {'Мужчины выше' if diff>0 else 'Женщины выше'} на {abs(diff):.2f} (p={p_val:.3f})")
        else:
            print(f"    {metric}: нет значимых различий (p={p_val:.3f})")

# ============= 4. ВИЗУАЛИЗАЦИЯ =============
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Стресс по активности
sns.boxplot(x='activity', y='stress', data=df, ax=axes[0,0], palette='Set2')
axes[0,0].set_title('Стресс по уровню активности', fontsize=12)

# Стресс по проживанию
sns.boxplot(x='living', y='stress', data=df, ax=axes[0,1], palette='Set3')
axes[0,1].set_title('Стресс по типу проживания', fontsize=12)

# Сон vs стресс
sns.scatterplot(x='sleep_hours', y='stress', hue='gender', data=df, ax=axes[1,0], s=100, alpha=0.7)
axes[1,0].set_title('Связь сна и стресса', fontsize=12)

# Удовлетворенность vs стресс
sns.scatterplot(x='satisfaction', y='stress', hue='gender', data=df, ax=axes[1,1], s=100, alpha=0.7)
axes[1,1].set_title('Удовлетворенность и стресс', fontsize=12)

plt.tight_layout()
plt.show()

# ============= 5. КЛАСТЕРИЗАЦИЯ =============
print("\n" + "="*60)
print("КЛАСТЕРИЗАЦИЯ СТУДЕНТОВ")
print("="*60)

# Подготовка данных для кластеризации
features = ['stress','satisfaction','sleep_hours','study_hours','sport',
            'procrastination','fatigue','free_time','interest_for_study']
# Проверяем наличие всех признаков
available_features = [f for f in features if f in df.columns]
print(f"✅ Используем признаки: {available_features}")

X = StandardScaler().fit_transform(df[available_features])

# PCA и t-SNE для визуализации
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X)
print(f"✅ PCA объясняет {pca.explained_variance_ratio_.sum():.1%} дисперсии")

perplexity = min(20, n-1)
tsne = TSNE(n_components=2, random_state=42, perplexity=perplexity)
X_tsne = tsne.fit_transform(X)
print(f"✅ t-SNE выполнено (perplexity={perplexity})")

# K-MEANS с подбором k
print("\n📊 K-MEANS:")
scores = []
k_range = range(2, min(6, n))
for k in k_range:
    labels = KMeans(n_clusters=k, random_state=42, n_init=10).fit_predict(X)
    score = silhouette_score(X, labels)
    scores.append(score)
    print(f"  k={k}: silhouette={score:.3f}")

best_k = k_range[np.argmax(scores)]
print(f"\n✨ Оптимальное k = {best_k}")

kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
df['cluster_kmeans'] = kmeans.fit_predict(X)

# ИЕРАРХИЧЕСКАЯ
print("\n📊 ИЕРАРХИЧЕСКАЯ:")
hier = AgglomerativeClustering(n_clusters=best_k, metric='euclidean', linkage='ward')
df['cluster_hier'] = hier.fit_predict(X)

# Дендрограмма
plt.figure(figsize=(12, 5))
linked = linkage(X, method='ward')
dendrogram(linked, truncate_mode='lastp', p=30, leaf_rotation=90, leaf_font_size=8)
plt.title('Дендрограмма (иерархическая кластеризация)', fontsize=12)
plt.xlabel('Индексы студентов')
plt.ylabel('Расстояние')
plt.axhline(y=5, color='r', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# DBSCAN
print("\n📊 DBSCAN:")
best_db = None
best_score = -1
for eps in [0.8, 1.0, 1.2, 1.5]:
    for min_samples in [2, 3, 4]:
        labels = DBSCAN(eps=eps, min_samples=min_samples).fit_predict(X)
        n_clust = len(set(labels)) - (1 if -1 in labels else 0)
        n_noise = list(labels).count(-1)
        if 2 <= n_clust <= 5:
            mask = labels != -1
            if sum(mask) > 1:
                try:
                    score = silhouette_score(X[mask], labels[mask])
                    print(f"  eps={eps}, min_samples={min_samples}: кластеров={n_clust}, шум={n_noise}, score={score:.3f}")
                    if score > best_score:
                        best_score, best_db = score, (eps, min_samples, labels)
                except:
                    print(f"  eps={eps}, min_samples={min_samples}: кластеров={n_clust}, шум={n_noise}")

if best_db:
    eps, ms, labels = best_db
    df['cluster_dbscan'] = labels
    print(f"\n✨ Лучший DBSCAN: eps={eps}, min_samples={ms}, выбросов={list(labels).count(-1)}")

# Визуализация кластеров
fig, axes = plt.subplots(2, 2, figsize=(14, 12))

# K-Means на PCA
scatter = axes[0,0].scatter(X_pca[:,0], X_pca[:,1], c=df['cluster_kmeans'], cmap='viridis', s=100, alpha=0.7)
axes[0,0].set_title(f'K-Means (k={best_k}) - PCA', fontsize=12)
axes[0,0].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.1%})')
axes[0,0].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.1%})')
plt.colorbar(scatter, ax=axes[0,0])

# K-Means на t-SNE
scatter = axes[0,1].scatter(X_tsne[:,0], X_tsne[:,1], c=df['cluster_kmeans'], cmap='viridis', s=100, alpha=0.7)
axes[0,1].set_title(f'K-Means (k={best_k}) - t-SNE', fontsize=12)
axes[0,1].set_xlabel('t-SNE 1')
axes[0,1].set_ylabel('t-SNE 2')
plt.colorbar(scatter, ax=axes[0,1])

# Иерархическая на PCA
scatter = axes[1,0].scatter(X_pca[:,0], X_pca[:,1], c=df['cluster_hier'], cmap='plasma', s=100, alpha=0.7)
axes[1,0].set_title(f'Иерархическая (k={best_k}) - PCA', fontsize=12)
axes[1,0].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.1%})')
axes[1,0].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.1%})')
plt.colorbar(scatter, ax=axes[1,0])

# DBSCAN на PCA (если есть)
if best_db:
    scatter = axes[1,1].scatter(X_pca[:,0], X_pca[:,1], c=df['cluster_dbscan'], cmap='tab10', s=100, alpha=0.7)
    axes[1,1].set_title(f'DBSCAN - PCA (выбросов: {list(df["cluster_dbscan"]).count(-1)})', fontsize=12)
    axes[1,1].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.1%})')
    axes[1,1].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.1%})')
    plt.colorbar(scatter, ax=axes[1,1])
else:
    axes[1,1].text(0.5, 0.5, 'DBSCAN не дал\nоптимальных результатов',
                   ha='center', va='center', transform=axes[1,1].transAxes, fontsize=12)
    axes[1,1].set_title('DBSCAN', fontsize=12)

plt.tight_layout()
plt.show()

# ============= 6. АНАЛИЗ КЛАСТЕРОВ =============
print("\n" + "="*60)
print("АНАЛИЗ КЛАСТЕРОВ (K-Means)")
print("="*60)

for c in sorted(df['cluster_kmeans'].unique()):
    cluster = df[df['cluster_kmeans'] == c]
    size = len(cluster)

    print(f"\n{'='*50}")
    print(f"КЛАСТЕР {c}: {size} студентов ({size/n*100:.1f}%)")
    print(f"{'='*50}")

    print(f"\n  Психологическое состояние:")
    print(f"    • Стресс: {cluster['stress'].mean():.2f}/3")
    print(f"    • Удовлетворенность: {cluster['satisfaction'].mean():.2f}/3")
    print(f"    • Прокрастинация: {cluster['procrastination'].mean():.2f}/3")
    print(f"    • Интерес к учебе: {cluster['interest_for_study'].mean():.2f}/3")

    print(f"\n  Образ жизни:")
    print(f"    • Сон: {cluster['sleep_hours'].mean():.2f}/3")
    print(f"    • Учеба: {cluster['study_hours'].mean():.2f}/3")
    print(f"    • Спорт: {cluster['sport'].mean():.2f}/3")
    print(f"    • Усталость: {cluster['fatigue'].mean():.2f}/3")
    print(f"    • Свободное время: {cluster['free_time'].mean():.2f}/3")

    print(f"\n  Социальные факторы:")
    print(f"    • Мужчины: {cluster['gender_male'].mean()*100:.0f}%")
    print(f"    • Живут с семьей: {cluster['living_семья'].mean()*100:.0f}%")
    print(f"    • Высокая активность: {cluster['activities_high'].mean()*100:.0f}%")

    # Характеристика
    if cluster['stress'].mean() > 2.2:
        print(f"\n  🚨 ХАРАКТЕРИСТИКА: ГРУППА ВЫСОКОГО РИСКА!")
        print(f"     → Требуется психологическая поддержка")
    elif cluster['stress'].mean() > 1.8:
        print(f"\n  ⚠️ ХАРАКТЕРИСТИКА: СРЕДНИЙ УРОВЕНЬ СТРЕССА")
        print(f"     → Рекомендуются профилактические меры")
    else:
        print(f"\n  😊 ХАРАКТЕРИСТИКА: БЛАГОПОЛУЧНАЯ ГРУППА")
        print(f"     → Хорошее психологическое состояние")

# ============= 7. СРАВНЕНИЕ МЕТОДОВ =============
print("\n" + "="*60)
print("СРАВНЕНИЕ МЕТОДОВ КЛАСТЕРИЗАЦИИ")
print("="*60)

print("\n📊 Сравнение K-Means и Иерархической:")
crosstab = pd.crosstab(df['cluster_kmeans'], df['cluster_hier'])
print(crosstab)

if best_db:
    print(f"\n📊 Сравнение K-Means и DBSCAN:")
    print(pd.crosstab(df['cluster_kmeans'], df['cluster_dbscan']))

# ============= 8. ИТОГОВЫЕ ВЫВОДЫ =============
print("\n" + "="*60)
print("ИТОГОВЫЕ ВЫВОДЫ")
print("="*60)

n_dbscan_noise = list(df['cluster_dbscan']).count(-1) if best_db else 0
very_high_stress = len(df[df['stress']>2.5])

print(f"""
📊 ОБЩАЯ СТАТИСТИКА ПО {n} СТУДЕНТАМ:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Средний стресс: {df['stress'].mean():.2f}/3
• Высокий стресс (>2): {high_stress} ({high_stress/n*100:.0f}%)
• Критический стресс (>2.5): {very_high_stress} ({very_high_stress/n*100:.0f}%)

🔍 РЕЗУЛЬТАТЫ КЛАСТЕРИЗАЦИИ:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Оптимальное число кластеров: k = {best_k}
• K-Means выделил {best_k} типа студентов
• Дендрограмма подтверждает структуру данных
""")

if best_db:
    print(f"• DBSCAN выявил {n_dbscan_noise} студентов-выбросов")

print(f"""
💡 КЛЮЧЕВЫЕ ФАКТОРЫ:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
СНИЖАЮТ СТРЕСС:
1. {negative_corr.index[0] if len(negative_corr) > 0 else 'N/A'}: {negative_corr.values[0] if len(negative_corr) > 0 else 0:.3f}
2. {negative_corr.index[1] if len(negative_corr) > 1 else 'N/A'}: {negative_corr.values[1] if len(negative_corr) > 1 else 0:.3f}

ПОВЫШАЮТ СТРЕСС:
1. {positive_corr.index[-1] if len(positive_corr) > 0 else 'N/A'}: {positive_corr.values[-1] if len(positive_corr) > 0 else 0:.3f}
2. {positive_corr.index[-2] if len(positive_corr) > 1 else 'N/A'}: {positive_corr.values[-2] if len(positive_corr) > 1 else 0:.3f}

🎯 РЕКОМЕНДАЦИИ:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Студенты с высоким стрессом ({high_stress} чел) нуждаются в психологической поддержке
2. Рекомендуется организовать группы поддержки для студентов из кластеров риска
3. Провести тренинги по управлению стрессом
""")

# Сохранение результатов
df.to_csv('student_clusters_full.csv', index=False)
print(f"\n✅ Полные результаты сохранены в 'student_clusters_full.csv'")
print(f"✅ Файл содержит {len(df.columns)} колонок с метками кластеров")