# -*- coding: utf-8 -*-
"""малик -5 лабка .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQ_YRQuOSCNwOxJJLJATdgMoSua8XwAA
"""

# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# 1. ЗАГРУЗКА ДАННЫХ
iris = load_iris()
X, y = iris.data, iris.target
feature_names = iris.feature_names
target_names = iris.target_names

print("="*55)
print("ЛАБОРАТОРНАЯ РАБОТА №5 - ВАРИАНТ 1")
print("Классификация ирисов")
print("="*55)

print(f"\nДатасет Iris:")
print(f"  Образцов: {X.shape[0]}")
print(f"  Признаков: {X.shape[1]} ({', '.join(feature_names)})")
print(f"  Классов: {len(target_names)} ({', '.join(target_names)})")

# 2. РАЗДЕЛЕНИЕ НА TRAIN/TEST
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nРазделение: обучение {len(X_train)} / тест {len(X_test)}")

# 3. ОБУЧЕНИЕ МОДЕЛЕЙ
print("\n" + "="*55)
print("РЕЗУЛЬТАТЫ МОДЕЛЕЙ")
print("="*55)

results = {}

# Decision Tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

results['Decision Tree'] = {
    'Accuracy': accuracy_score(y_test, y_pred_dt),
    'Precision': precision_score(y_test, y_pred_dt, average='macro'),
    'Recall': recall_score(y_test, y_pred_dt, average='macro'),
    'F1': f1_score(y_test, y_pred_dt, average='macro')
}

# Random Forest (10, 50, 100)
for n in [10, 50, 100]:
    rf = RandomForestClassifier(n_estimators=n, random_state=42)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    results[f'RF ({n})'] = {
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred, average='macro'),
        'Recall': recall_score(y_test, y_pred, average='macro'),
        'F1': f1_score(y_test, y_pred, average='macro')
    }
    if n == 100:
        rf_best = rf  # сохраняем для важности признаков

# Bagging
bag = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50, random_state=42)
bag.fit(X_train, y_train)
y_pred_bag = bag.predict(X_test)

results['Bagging (50)'] = {
    'Accuracy': accuracy_score(y_test, y_pred_bag),
    'Precision': precision_score(y_test, y_pred_bag, average='macro'),
    'Recall': recall_score(y_test, y_pred_bag, average='macro'),
    'F1': f1_score(y_test, y_pred_bag, average='macro')
}

# Вывод результатов
for model, metrics in results.items():
    print(f"\n{model}:")
    print(f"  Accuracy: {metrics['Accuracy']:.4f}")
    print(f"  Precision: {metrics['Precision']:.4f}")
    print(f"  Recall: {metrics['Recall']:.4f}")
    print(f"  F1-score: {metrics['F1']:.4f}")

# 4. СВОДНАЯ ТАБЛИЦА
print("\n" + "="*55)
print("СВОДНАЯ ТАБЛИЦА")
print("="*55)

print(f"{'Модель':<18} {'Acc':<8} {'Prec':<8} {'Rec':<8} {'F1':<8}")
print("-"*55)
for model, m in results.items():
    print(f"{model:<18} {m['Accuracy']:<8.4f} {m['Precision']:<8.4f} {m['Recall']:<8.4f} {m['F1']:<8.4f}")

# 5. ГРАФИКИ
print("\n" + "="*55)
print("ВИЗУАЛИЗАЦИЯ")
print("="*55)

# График 1: Сравнение F1-score
plt.figure(figsize=(10, 5))

models = list(results.keys())
f1_scores = [results[m]['F1'] for m in models]

plt.subplot(1, 2, 1)
bars = plt.bar(models, f1_scores, color=['gray', 'steelblue', 'steelblue', 'steelblue', 'coral'])
plt.xticks(rotation=45)
plt.ylabel('F1-score')
plt.title('Сравнение F1-score')
plt.ylim(0, 1)
for bar, val in zip(bars, f1_scores):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{val:.3f}', ha='center', va='bottom')

# График 2: Влияние числа деревьев
rf_models = ['RF (10)', 'RF (50)', 'RF (100)']
rf_f1 = [results[m]['F1'] for m in rf_models]

plt.subplot(1, 2, 2)
plt.plot([10, 50, 100], rf_f1, 'bo-', linewidth=2, markersize=8)
plt.xlabel('Количество деревьев')
plt.ylabel('F1-score')
plt.title('Влияние числа деревьев на качество')
plt.grid(True, alpha=0.3)
plt.ylim(0.9, 1.01)

plt.tight_layout()
plt.show()

# График 3: Важность признаков
plt.figure(figsize=(8, 5))
importance = rf_best.feature_importances_
plt.barh(feature_names, importance, color='green', alpha=0.7)
plt.xlabel('Важность')
plt.title('Важность признаков (Random Forest, 100 деревьев)')
for i, (name, imp) in enumerate(zip(feature_names, importance)):
    plt.text(imp + 0.01, i, f'{imp:.3f}', va='center')
plt.tight_layout()
plt.show()

# График 4: Матрица ошибок (для лучшей модели)
plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_test, rf_best.predict(X_test))
plt.imshow(cm, cmap='Blues', interpolation='nearest')
plt.colorbar()
plt.title('Матрица ошибок (Random Forest, 100 деревьев)')
plt.xticks([0, 1, 2], target_names, rotation=45)
plt.yticks([0, 1, 2], target_names)
plt.xlabel('Предсказано')
plt.ylabel('Фактически')

for i in range(3):
    for j in range(3):
        plt.text(j, i, cm[i, j], ha='center', va='center', fontsize=14)
plt.tight_layout()
plt.show()

# 6. ВЫВОДЫ
print("\n" + "="*55)
print("ВЫВОДЫ")
print("="*55)

print(f"\nЛучшая модель: Random Forest (100 деревьев)")
print(f"  F1-score: {results['RF (100)']['F1']:.4f}")
print(f"  Accuracy: {results['RF (100)']['Accuracy']:.4f}")

print("\nКлючевые наблюдения:")
print("1. Ансамблевые методы (RF, Bagging) работают лучше одиночного дерева")
print("2. При увеличении деревьев с 10 до 100 качество растет и выходит на плато")
print("3. Самый важный признак: petal width (ширина лепестка)")
print("4. Все модели показали отличные результаты (Iris - простой датасет)")

# 7. ОТВЕТЫ НА КОНТРОЛЬНЫЕ ВОПРОСЫ
print("\n" + "="*55)
print("КОНТРОЛЬНЫЕ ВОПРОСЫ")
print("="*55)

print("\n1. Отличие Bagging от одиночного дерева:")
print("   - Одиночное дерево: одна модель на всех данных")
print("   - Bagging: много деревьев на разных подвыборках, голосование")
print("   - Bagging уменьшает переобучение и повышает стабильность")

print("\n2. Feature importance в Random Forest:")
print("   - Считает, насколько признак уменьшает неопределенность (Gini impurity)")
print("   - Усредняет по всем деревьям")
print("   - Сумма всех важностей = 1")

print("\n3. Если убрать самый важный признак (petal width):")
print("   - Точность упадет, так как это ключевой признак для разделения видов")
print("   - Модель будет больше полагаться на petal length и другие признаки")

print("\n4. Почему точность выходит на плато:")
print("   - Первые деревья: учатся на новых данных, исправляют ошибки")
print("   - После 50-100 деревьев: новые деревья уже не дают новой информации")
print("   - Дальнейшее увеличение только замедляет обучение без улучшения")

print("\n" + "="*55)
print("ЛАБОРАТОРНАЯ РАБОТА ВЫПОЛНЕНА")
print("="*55)