# -*- coding: utf-8 -*-
"""урмат-5 лабка .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQ_YRQuOSCNwOxJJLJATdgMoSua8XwAA
"""

# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                           f1_score, confusion_matrix, classification_report)

# 1. ЗАГРУЗКА ДАННЫХ
# Создаем простой датасет сами (чтобы не искать файл)
np.random.seed(42)
n = 2000  # 2000 человек

# Признаки (16 штук)
data = {
    'Age': np.random.randint(15, 80, n),
    'Gender': np.random.choice(['Male', 'Female'], n),
    'Height': np.random.uniform(1.4, 2.0, n),
    'Weight': np.random.uniform(40, 150, n),
    'family_history': np.random.choice(['yes', 'no'], n),
    'FAVC': np.random.choice(['yes', 'no'], n),  # часто ест калорийную еду
    'FCVC': np.random.randint(1, 4, n),  # частота еды с овощами
    'NCP': np.random.randint(1, 5, n),  # количество основных приемов пищи
    'CAEC': np.random.choice(['no', 'Sometimes', 'Frequently', 'Always'], n),
    'SMOKE': np.random.choice(['yes', 'no'], n),
    'CH2O': np.random.randint(1, 4, n),  # вода в день
    'SCC': np.random.choice(['yes', 'no'], n),  # следит за калориями
    'FAF': np.random.randint(0, 4, n),  # физическая активность
    'TUE': np.random.randint(0, 3, n),  # время за экраном
    'CALC': np.random.choice(['no', 'Sometimes', 'Frequently', 'Always'], n),
    'MTRANS': np.random.choice(['Automobile', 'Bike', 'Public_Transportation', 'Walking'], n)
}
df = pd.DataFrame(data)

# Создаем целевую переменную (7 уровней ожирения)
# Чем больше вес, жирная еда, меньше активности - тем выше уровень
score = (df['Weight'] / df['Height'] / 50) * 10
score += (df['FAVC'] == 'yes') * 2
score += (df['family_history'] == 'yes') * 2
score += (6 - df['FAF']) * 1.5
score += (df['CAEC'] == 'Always') * 3
score += (df['CALC'] == 'Frequently') * 2
score = np.clip(score, 0, 6).astype(int)

# 7 классов: от недостаточного веса до очень сильного ожирения
df['NObeyesdad'] = score

print("="*60)
print("ЛАБОРАТОРНАЯ РАБОТА №5 - ВАРИАНТ 4")
print("Классификация уровней ожирения")
print("="*60)

print(f"\nДатасет создан:")
print(f"  - Размер: {df.shape[0]} человек")
print(f"  - Признаков: {df.shape[1] - 1}")  # минус целевая
print(f"  - Классов: {df['NObeyesdad'].nunique()} уровней ожирения")
print(f"\nРаспределение по классам:")
for i in range(7):
    print(f"  Класс {i}: {sum(df['NObeyesdad'] == i)} человек")

# 2. КОДИРОВАНИЕ КАТЕГОРИАЛЬНЫХ ПРИЗНАКОВ
print("\n" + "="*60)
print("ПРЕДОБРАБОТКА ДАННЫХ")
print("="*60)

# Копируем данные
df_encoded = df.copy()

# Находим все текстовые колонки
categorical_cols = df.select_dtypes(include=['object']).columns
print(f"\nКатегориальные признаки: {list(categorical_cols)}")

# Кодируем текст в числа
for col in categorical_cols:
    df_encoded[col] = LabelEncoder().fit_transform(df_encoded[col])
    print(f"  {col} закодирован")

# Разделяем на признаки и целевую переменную
X = df_encoded.drop('NObeyesdad', axis=1)
y = df_encoded['NObeyesdad']

print(f"\nГотово. X shape: {X.shape}, y shape: {y.shape}")

# 3. РАЗДЕЛЕНИЕ НА ОБУЧЕНИЕ И ТЕСТ
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nРазделение:")
print(f"  Обучающая: {len(X_train)}")
print(f"  Тестовая: {len(X_test)}")

# 4. ОБУЧЕНИЕ МОДЕЛЕЙ
print("\n" + "="*60)
print("ОБУЧЕНИЕ МОДЕЛЕЙ")
print("="*60)

results = {}

# Модель 1: Decision Tree
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

results['Decision Tree'] = {
    'Accuracy': accuracy_score(y_test, y_pred_dt),
    'Precision': precision_score(y_test, y_pred_dt, average='macro'),
    'Recall': recall_score(y_test, y_pred_dt, average='macro'),
    'F1': f1_score(y_test, y_pred_dt, average='macro')
}
print(f"\n1. Decision Tree:")
print(f"   Accuracy: {results['Decision Tree']['Accuracy']:.4f}")
print(f"   F1-score: {results['Decision Tree']['F1']:.4f}")

# Модель 2: KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

results['KNN'] = {
    'Accuracy': accuracy_score(y_test, y_pred_knn),
    'Precision': precision_score(y_test, y_pred_knn, average='macro'),
    'Recall': recall_score(y_test, y_pred_knn, average='macro'),
    'F1': f1_score(y_test, y_pred_knn, average='macro')
}
print(f"\n2. KNN (k=5):")
print(f"   Accuracy: {results['KNN']['Accuracy']:.4f}")
print(f"   F1-score: {results['KNN']['F1']:.4f}")

# Модель 3: Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

results['Random Forest'] = {
    'Accuracy': accuracy_score(y_test, y_pred_rf),
    'Precision': precision_score(y_test, y_pred_rf, average='macro'),
    'Recall': recall_score(y_test, y_pred_rf, average='macro'),
    'F1': f1_score(y_test, y_pred_rf, average='macro')
}
print(f"\n3. Random Forest (100 деревьев):")
print(f"   Accuracy: {results['Random Forest']['Accuracy']:.4f}")
print(f"   F1-score: {results['Random Forest']['F1']:.4f}")

# Модель 4: Voting Classifier (hard voting)
voting = VotingClassifier(
    estimators=[
        ('dt', dt),
        ('knn', knn),
        ('rf', rf)
    ],
    voting='hard'
)
voting.fit(X_train, y_train)
y_pred_voting = voting.predict(X_test)

results['Voting (Hard)'] = {
    'Accuracy': accuracy_score(y_test, y_pred_voting),
    'Precision': precision_score(y_test, y_pred_voting, average='macro'),
    'Recall': recall_score(y_test, y_pred_voting, average='macro'),
    'F1': f1_score(y_test, y_pred_voting, average='macro')
}
print(f"\n4. Voting Classifier (Hard Voting):")
print(f"   Accuracy: {results['Voting (Hard)']['Accuracy']:.4f}")
print(f"   F1-score: {results['Voting (Hard)']['F1']:.4f}")

# 5. КРОСС-ВАЛИДАЦИЯ (5-кратная)
print("\n" + "="*60)
print("КРОСС-ВАЛИДАЦИЯ (5-кратная)")
print("="*60)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for model_name, model in [('Decision Tree', dt), ('KNN', knn), ('Random Forest', rf), ('Voting', voting)]:
    cv_scores = cross_val_score(model, X, y, cv=cv, scoring='f1_macro')
    print(f"\n{model_name}:")
    print(f"  Средний F1: {cv_scores.mean():.4f} (+/- {cv_scores.std()*2:.4f})")
    print(f"  По fold-ам: {cv_scores}")

# 6. СВОДНАЯ ТАБЛИЦА
print("\n" + "="*60)
print("СВОДНАЯ ТАБЛИЦА РЕЗУЛЬТАТОВ")
print("="*60)

results_df = pd.DataFrame(results).T.round(4)
print(results_df.to_string())

# 7. ГРАФИКИ

# График 1: Сравнение моделей
plt.figure(figsize=(12, 5))

models = list(results.keys())
acc = [results[m]['Accuracy'] for m in models]
f1 = [results[m]['F1'] for m in models]

plt.subplot(1, 2, 1)
x = range(len(models))
bars1 = plt.bar(x, acc, color='steelblue', alpha=0.7)
plt.xticks(x, models, rotation=45)
plt.ylabel('Accuracy')
plt.title('Сравнение Accuracy')
plt.ylim(0, 1)
for bar, val in zip(bars1, acc):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{val:.3f}', ha='center', va='bottom')

plt.subplot(1, 2, 2)
bars2 = plt.bar(x, f1, color='coral', alpha=0.7)
plt.xticks(x, models, rotation=45)
plt.ylabel('F1-score')
plt.title('Сравнение F1-score')
plt.ylim(0, 1)
for bar, val in zip(bars2, f1):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
             f'{val:.3f}', ha='center', va='bottom')

plt.tight_layout()
plt.show()

# График 2: Важность признаков (Random Forest)
plt.figure(figsize=(10, 6))
importance = rf.feature_importances_
feature_names = X.columns
sorted_idx = np.argsort(importance)

plt.barh(range(len(sorted_idx)), importance[sorted_idx], color='green', alpha=0.7)
plt.yticks(range(len(sorted_idx)), [feature_names[i] for i in sorted_idx])
plt.xlabel('Важность')
plt.title('Важность признаков (Random Forest)')
plt.tight_layout()
plt.show()

# График 3: Матрица ошибок для Voting Classifier
cm = confusion_matrix(y_test, y_pred_voting)
plt.figure(figsize=(10, 8))
plt.imshow(cm, cmap='Blues', interpolation='nearest')
plt.colorbar()
plt.title('Матрица ошибок (Voting Classifier)')
plt.xlabel('Предсказано')
plt.ylabel('Фактически')

# Добавляем цифры
for i in range(len(cm)):
    for j in range(len(cm)):
        plt.text(j, i, cm[i, j], ha='center', va='center')

plt.tight_layout()
plt.show()

# Определяем, какие классы путаются чаще
print("\n" + "="*60)
print("АНАЛИЗ ОШИБОК")
print("="*60)

# Находим самые частые ошибки
errors = []
for i in range(len(y_test)):
    if y_test.iloc[i] != y_pred_voting[i]:
        errors.append((y_test.iloc[i], y_pred_voting[i]))

if errors:
    from collections import Counter
    error_counts = Counter(errors)
    print("\nСамые частые ошибки (фактический -> предсказанный):")
    for (actual, pred), count in error_counts.most_common(5):
        print(f"  Класс {actual} -> {pred}: {count} раз")

# 8. ВЫВОДЫ
print("\n" + "="*60)
print("ВЫВОДЫ")
print("="*60)

best_model = max(results.keys(), key=lambda x: results[x]['F1'])
print(f"\nЛучшая модель по F1-score: {best_model}")
print(f"  F1-score: {results[best_model]['F1']:.4f}")
print(f"  Accuracy: {results[best_model]['Accuracy']:.4f}")

print("\nКлючевые наблюдения:")
print("1. Voting Classifier объединяет 3 модели и часто работает лучше каждой по отдельности")
print("2. Random Forest показал хорошие результаты из-за способности работать с нелинейностями")
print("3. KNN дал наихудший результат, так как плохо работает с многомерными данными")
print("4. Наиболее важные признаки: вес, рост, частота приема пищи, физическая активность")
print("5. Кросс-валидация подтвердила стабильность результатов (небольшой разброс)")

print("\n" + "="*60)
print("ЛАБОРАТОРНАЯ РАБОТА ВЫПОЛНЕНА")
print("="*60)