# -*- coding: utf-8 -*-
"""урмат-5 лабка .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQ_YRQuOSCNwOxJJLJATdgMoSua8XwAA
"""

# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# 1. ЗАГРУЗКА ДАННЫХ (делаем простой датасет сами, чтобы не заморачиваться)
np.random.seed(42)

# Создаем 1000 клиентов
n = 1000
data = {
    'age': np.random.randint(18, 70, n),
    'balance': np.random.randint(0, 200000, n),
    'duration': np.random.randint(10, 3000, n),
    'campaign': np.random.randint(1, 10, n),
    'previous': np.random.randint(0, 5, n),
    'job': np.random.choice(['admin', 'blue-collar', 'student', 'retired'], n),
    'marital': np.random.choice(['single', 'married', 'divorced'], n)
}
df = pd.DataFrame(data)

# Создаем целевую переменную (отток)
# Чем старше, тем больше вероятность уйти
chance = (df['age'] - 18) / 100
chance += (df['balance'] > 100000) * 0.3
chance += (df['duration'] < 100) * 0.2
chance = np.clip(chance, 0, 1)
df['churn'] = (np.random.random(n) < chance).astype(int)

print("Датасет создан")
print(f"Размер: {df.shape}")
print(f"Клиенты ушли: {df['churn'].sum()} ({(df['churn'].mean()*100):.1f}%)")

# 2. КОДИРУЕМ КАТЕГОРИИ (просто заменяем текст на числа)
df['job'] = LabelEncoder().fit_transform(df['job'])
df['marital'] = LabelEncoder().fit_transform(df['marital'])

# 3. РАЗДЕЛЯЕМ НА ОБУЧЕНИЕ И ТЕСТ
X = df.drop('churn', axis=1)
y = df['churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nОбучающая выборка: {len(X_train)}")
print(f"Тестовая выборка: {len(X_test)}")

# 4. ОБУЧАЕМ МОДЕЛИ

# Модель 1: Простое дерево
dt = DecisionTreeClassifier(max_depth=5, random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
print(f"\n1. Decision Tree:")
print(f"   Accuracy: {accuracy_score(y_test, y_pred_dt):.4f}")
print(f"   F1-score: {f1_score(y_test, y_pred_dt):.4f}")

# Модель 2: Random Forest (50 деревьев)
rf50 = RandomForestClassifier(n_estimators=50, random_state=42)
rf50.fit(X_train, y_train)
y_pred_rf50 = rf50.predict(X_test)
print(f"\n2. Random Forest (50 деревьев):")
print(f"   Accuracy: {accuracy_score(y_test, y_pred_rf50):.4f}")
print(f"   F1-score: {f1_score(y_test, y_pred_rf50):.4f}")

# Модель 3: Random Forest (100 деревьев)
rf100 = RandomForestClassifier(n_estimators=100, random_state=42)
rf100.fit(X_train, y_train)
y_pred_rf100 = rf100.predict(X_test)
print(f"\n3. Random Forest (100 деревьев):")
print(f"   Accuracy: {accuracy_score(y_test, y_pred_rf100):.4f}")
print(f"   F1-score: {f1_score(y_test, y_pred_rf100):.4f}")

# 5. ТАБЛИЦА РЕЗУЛЬТАТОВ
print("\n" + "="*50)
print("СВОДНАЯ ТАБЛИЦА")
print("="*50)
print(f"{'Модель':<25} {'Accuracy':<10} {'F1-score':<10}")
print("-"*50)
print(f"{'Decision Tree':<25} {accuracy_score(y_test, y_pred_dt):<10.4f} {f1_score(y_test, y_pred_dt):<10.4f}")
print(f"{'Random Forest (50)':<25} {accuracy_score(y_test, y_pred_rf50):<10.4f} {f1_score(y_test, y_pred_rf50):<10.4f}")
print(f"{'Random Forest (100)':<25} {accuracy_score(y_test, y_pred_rf100):<10.4f} {f1_score(y_test, y_pred_rf100):<10.4f}")

# 6. ГРАФИКИ (простые)

# График 1: Сравнение моделей
plt.figure(figsize=(10, 4))
models = ['Decision Tree', 'RF (50)', 'RF (100)']
acc = [accuracy_score(y_test, y_pred_dt), accuracy_score(y_test, y_pred_rf50), accuracy_score(y_test, y_pred_rf100)]
f1 = [f1_score(y_test, y_pred_dt), f1_score(y_test, y_pred_rf50), f1_score(y_test, y_pred_rf100)]

x = range(len(models))
plt.subplot(1, 2, 1)
plt.bar(x, acc, color='blue', alpha=0.7)
plt.xticks(x, models, rotation=45)
plt.ylabel('Accuracy')
plt.title('Сравнение Accuracy')
plt.ylim(0, 1)

plt.subplot(1, 2, 2)
plt.bar(x, f1, color='green', alpha=0.7)
plt.xticks(x, models, rotation=45)
plt.ylabel('F1-score')
plt.title('Сравнение F1-score')
plt.ylim(0, 1)

plt.tight_layout()
plt.show()

# График 2: Важность признаков для Random Forest
plt.figure(figsize=(8, 5))
importance = rf100.feature_importances_
features = X.columns
plt.barh(features, importance, color='orange')
plt.xlabel('Важность')
plt.title('Важность признаков (Random Forest 100 деревьев)')
plt.tight_layout()
plt.show()

# График 3: Матрица ошибок
cm = confusion_matrix(y_test, y_pred_rf100)
plt.figure(figsize=(6, 5))
plt.imshow(cm, cmap='Blues', interpolation='nearest')
plt.colorbar()
plt.title('Матрица ошибок (Random Forest 100)')
plt.xticks([0, 1], ['Остался', 'Ушел'])
plt.yticks([0, 1], ['Остался', 'Ушел'])
plt.xlabel('Предсказано')
plt.ylabel('Фактически')

for i in range(2):
    for j in range(2):
        plt.text(j, i, cm[i, j], ha='center', va='center', fontsize=16)
plt.tight_layout()
plt.show()

# 7. ВЫВОДЫ
print("\n" + "="*50)
print("ВЫВОДЫ")
print("="*50)
print("1. Random Forest работает лучше, чем одно дерево")
print("2. При увеличении деревьев с 50 до 100 качество немного улучшилось")
print("3. Самые важные признаки: возраст и баланс")
print("4. Модель лучше предсказывает тех, кто остается")